// <auto-generated />
using System;
using Malayisha.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Malayisha.Infrastructure.Migrations
{
    [DbContext(typeof(MalayishaDbContext))]
    [Migration("20260715112238_AddBookingDeliveryRequestId")]
    partial class AddBookingDeliveryRequestId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Malayisha.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AgreedPriceZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agreed_price_zar");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<Guid?>("DeliveryRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_request_id");

                    b.Property<DateTime?>("InTransitAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("in_transit_at_utc");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<decimal?>("QuotedPriceZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quoted_price_zar");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_id");

                    b.Property<Guid>("TripListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_listing_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CancelledByUserId")
                        .HasDatabaseName("ix_bookings_cancelled_by_user_id");

                    b.HasIndex("DeliveryRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_delivery_request_id")
                        .HasFilter("delivery_request_id IS NOT NULL");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_bookings_sender_id");

                    b.HasIndex("TripListingId")
                        .HasDatabaseName("ix_bookings_trip_listing_id");

                    b.HasIndex("TransporterId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("idx_booking_transporter");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_chat_messages_booking_id");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_chat_messages_sender_user_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.CommissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AgreedPriceZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("agreed_price_zar");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("CommissionAmountZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_amount_zar");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CompletionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TransporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_user_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_admin_user_id");

                    b.HasKey("Id")
                        .HasName("pk_commission_records");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_commission_records_booking_id");

                    b.HasIndex("TransporterUserId")
                        .HasDatabaseName("ix_commission_records_transporter_user_id");

                    b.HasIndex("UpdatedByAdminUserId")
                        .HasDatabaseName("ix_commission_records_updated_by_admin_user_id");

                    b.HasIndex("Status", "CompletionDateUtc")
                        .HasDatabaseName("idx_commission_status_date");

                    b.ToTable("commission_records", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.DeliveryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("destination_city");

                    b.Property<string>("GoodsDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("goods_description");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("origin_city");

                    b.Property<DateTime>("RequiredDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("required_date_utc");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SizeDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("size_description");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_delivery_requests");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_delivery_requests_sender_id");

                    b.ToTable("delivery_requests", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.OtpRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consumed");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_otp_records");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("idx_otp_phone");

                    b.ToTable("otp_records", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<Guid>("TransporterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_profile_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_booking_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_reviews_sender_id");

                    b.HasIndex("TransporterProfileId", "IsHidden", "CreatedAtUtc")
                        .HasDatabaseName("idx_review_transporter");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.TransporterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("average_rating");

                    b.Property<decimal>("CapacityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_url");

                    b.PrimitiveCollection<string>("RoutesServed")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("routes_served");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("vehicle_description");

                    b.HasKey("Id")
                        .HasName("pk_transporter_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_transporter_profiles_user_id");

                    b.ToTable("transporter_profiles", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.TripListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableCapacityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("available_capacity_kg");

                    b.Property<DateTime?>("BoostEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("boost_end_at_utc");

                    b.Property<DateTime?>("BoostStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("boost_start_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("DepartureDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_date_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("destination_city");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boosted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("origin_city");

                    b.Property<decimal>("PriceGuideZar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_guide_zar");

                    b.Property<Guid>("TransporterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_profile_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_trip_listings");

                    b.HasIndex("TransporterProfileId")
                        .HasDatabaseName("ix_trip_listings_transporter_profile_id");

                    b.HasIndex("OriginCity", "DestinationCity", "DepartureDateUtc", "IsBoosted")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("idx_trip_search")
                        .HasFilter("is_deleted = false");

                    b.ToTable("trip_listings", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_admin_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("TransporterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporter_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_verifications");

                    b.HasIndex("ReviewedByAdminUserId")
                        .HasDatabaseName("ix_verifications_reviewed_by_admin_user_id");

                    b.HasIndex("TransporterProfileId")
                        .HasDatabaseName("ix_verifications_transporter_profile_id");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_users_cancelled_by_user_id");

                    b.HasOne("Malayisha.Domain.Entities.DeliveryRequest", null)
                        .WithMany()
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_delivery_requests_delivery_request_id");

                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_sender_id");

                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_transporter_id");

                    b.HasOne("Malayisha.Domain.Entities.TripListing", null)
                        .WithMany()
                        .HasForeignKey("TripListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trip_listings_trip_listing_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_bookings_booking_id");

                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_users_sender_user_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.CommissionRecord", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commission_records_bookings_booking_id");

                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TransporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commission_records_users_transporter_user_id");

                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_commission_records_users_updated_by_admin_user_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.DeliveryRequest", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_requests_users_sender_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.Review", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_booking_id");

                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_sender_id");

                    b.HasOne("Malayisha.Domain.Entities.TransporterProfile", null)
                        .WithMany()
                        .HasForeignKey("TransporterProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_transporter_profiles_transporter_profile_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.TransporterProfile", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transporter_profiles_users_user_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.TripListing", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.TransporterProfile", null)
                        .WithMany()
                        .HasForeignKey("TransporterProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_listings_transporter_profiles_transporter_profile_id");
                });

            modelBuilder.Entity("Malayisha.Domain.Entities.Verification", b =>
                {
                    b.HasOne("Malayisha.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_verifications_users_reviewed_by_admin_user_id");

                    b.HasOne("Malayisha.Domain.Entities.TransporterProfile", null)
                        .WithMany()
                        .HasForeignKey("TransporterProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verifications_transporter_profiles_transporter_profile_id");
                });
#pragma warning restore 612, 618
        }
    }
}
